### ISSUE TITLE
YOLOv5 weights

### ISSUE THREAD

**Issue by Calvinnncy97** [SampannaKahu/deepfigures-open#57]
Hi, 

May I know the weights for the YOLOv5 model is actually released? If yes, where can I get them?

Thank you.

Best regards,
Calvinn

**Comment by SampannaKahu** [comment]
Hi Calvinn,

Yes, the best shot of obtaining the weights would be to check the Docker images [here](https://hub.docker.com/r/sampyash/vt_cs_6604_digital_libraries/tags).

I haven't used Docker for a while now, so I might misremember, but it should be possible to pull one of the images from the above link, ssh/bash into it, and copy the weights to your host OS. Alternatively, you could try searching online on how to extract files from Docker images. [Here](https://forums.docker.com/t/how-to-extract-file-from-image/96987) is one potentially useful forum post I found.

Hoping this helps!

Best regards,
Sampanna

**Comment by Calvinnncy97** [comment]
Oh I see, didn't know that the weights are in the Docker image. Thank you for the info!
